// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: storage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Picture       string                 `protobuf:"bytes,1,opt,name=picture,proto3" json:"picture,omitempty"`
	Iat           float64                `protobuf:"fixed64,2,opt,name=iat,proto3" json:"iat,omitempty"`
	Exp           float64                `protobuf:"fixed64,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Iss           string                 `protobuf:"bytes,4,opt,name=iss,proto3" json:"iss,omitempty"`
	Azp           string                 `protobuf:"bytes,5,opt,name=azp,proto3" json:"azp,omitempty"`
	EmailVerified bool                   `protobuf:"varint,6,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	GivenName     string                 `protobuf:"bytes,8,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	Aud           string                 `protobuf:"bytes,9,opt,name=aud,proto3" json:"aud,omitempty"`
	Sub           string                 `protobuf:"bytes,10,opt,name=sub,proto3" json:"sub,omitempty"`
	Email         string                 `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	AtHash        string                 `protobuf:"bytes,12,opt,name=at_hash,json=atHash,proto3" json:"at_hash,omitempty"`
	Jwt           string                 `protobuf:"bytes,13,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *User) GetIat() float64 {
	if x != nil {
		return x.Iat
	}
	return 0
}

func (x *User) GetExp() float64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *User) GetIss() string {
	if x != nil {
		return x.Iss
	}
	return ""
}

func (x *User) GetAzp() string {
	if x != nil {
		return x.Azp
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *User) GetAud() string {
	if x != nil {
		return x.Aud
	}
	return ""
}

func (x *User) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAtHash() string {
	if x != nil {
		return x.AtHash
	}
	return ""
}

func (x *User) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x02pb\"\xa7\x02\n" +
	"\x04User\x12\x18\n" +
	"\apicture\x18\x01 \x01(\tR\apicture\x12\x10\n" +
	"\x03iat\x18\x02 \x01(\x01R\x03iat\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x01R\x03exp\x12\x10\n" +
	"\x03iss\x18\x04 \x01(\tR\x03iss\x12\x10\n" +
	"\x03azp\x18\x05 \x01(\tR\x03azp\x12%\n" +
	"\x0eemail_verified\x18\x06 \x01(\bR\remailVerified\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"given_name\x18\b \x01(\tR\tgivenName\x12\x10\n" +
	"\x03aud\x18\t \x01(\tR\x03aud\x12\x10\n" +
	"\x03sub\x18\n" +
	" \x01(\tR\x03sub\x12\x14\n" +
	"\x05email\x18\v \x01(\tR\x05email\x12\x17\n" +
	"\aat_hash\x18\f \x01(\tR\x06atHash\x12\x10\n" +
	"\x03jwt\x18\r \x01(\tR\x03jwtB\x06Z\x04./pbb\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storage_proto_goTypes = []any{
	(*User)(nil), // 0: pb.User
}
var file_storage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
