app:
  port: "3000"
  scheme: "http"
  dev_mode: true
  cookie_secure: false

providers:
  oauthserver:
    enabled: true
    port: "8080"
    issuer_url: "http://localhost:8080"
    client_id: "my-client"
    client_secret: "${OAUTH_SERVER_CLIENT_SECRET}"
    key_dir: "./keys"
    auth_html_path: "./templates/auth.html"
    verifyemail_html_path: "./templates/verifyemail.html"
    redirect_uris:
      - "http://localhost:3000/callback/oauthserver"
    tls:
      enabled: false
      cert_path: ""
      key_path: ""

  google:
    enabled: true
    auth_url: "https://accounts.google.com"
    client_id: "${GOOGLE_CLIENT_ID}"
    client_secret: "${GOOGLE_CLIENT_SECRET}"
    redirect_uri: "http://localhost:3000/callback/google"

jwt:
  secret: "replace-with-at-least-32-bytes-secret"
  cookie_name: "session_id"

storage:
  type: "mysql" # memory, mysql, postgres, sqlite
  connection_string: "${CONNECTION_STRING}"

logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, text

smtp:
  host: "smtp.resend.com"
  port: "465"
  username: "resend"
  password: "${SMTP_PASSWORD}"
  from: "admin@pwnhub.in"
